### ISSUE TITLE
Postgres: querying `isFuture`/[…] results in "column does not exist" error

### ISSUE THREAD

**Issue by denisyilmaz** [studioespresso/craft-date-range#48]
We have two projects, one running MariaDB 11.4 and one running PostgreSQL 16.
Both use the same CraftCMS and Daterange version.

When querying for entries using via `isFuture` etc. we get the following error on the instance running with PostgreSQL 16. Same query works flawlessly on the MariaDB instance.

```twig
{% set openingHours = craft.entries.type('openingHours').isNotPast('validity', 'openingHours')  %} 

{% if openingHours|length %}
    <ul>
        {% for exception in openingHours %}
            <li>{{ exception.title }}: {{ exception.validity }}</li>
        {% endfor %}
    </ul>
{% endif %}
```

The error is happening both in GraphQL as well as in Twig

```gql
query GetOpeningHours {
  entries(type: "openingHours", isNotPast: ["validity", "openingHours"]) {
    __typename
    ... on openingHours_Entry {
      id
      title
      typeHandle
      fieldHandle
      validity {
        start
        end
        isPast
        isNotPast
        isFuture
        isOnGoing
      }
    }
  }
}
```

The error from Twig, same applies to Graphql:
```bash
PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "field_validity" does not exist
LINE 8: ... NULL) AND ("elements"."revisionId" IS NULL) AND ("field_val...
                                                             ^ in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1320
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement->execute()
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute()
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(443): yii\db\Command->queryInternal()
#3 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2204): yii\db\Command->queryScalar()
#4 /var/www/html/vendor/yiisoft/yii2/db/Query.php(368): craft\elements\db\ElementQuery->queryScalar()
#5 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1834): yii\db\Query->count()
#6 /var/www/html/vendor/craftcms/cms/src/web/twig/Extension.php(1297): craft\elements\db\ElementQuery->count()
#7 /var/www/html/craftcms/storage/runtime/compiled_templates/cd/cd1962c1f56865a98b8fda8092c75b76.php(54): craft\web\twig\Extension->lengthFilter()
#8 /var/www/html/vendor/twig/twig/src/Template.php(393): __TwigTemplate_56f5971aba4fc24e0a1d37fb041ed5d6->doDisplay()
#9 /var/www/html/vendor/twig/twig/src/Template.php(349): Twig\Template->yield()
#10 /var/www/html/vendor/twig/twig/src/Template.php(364): Twig\Template->display()
#11 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render()
#12 /var/www/html/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render()
#13 /var/www/html/vendor/craftcms/cms/src/web/View.php(544): Twig\Environment->render()
#14 /var/www/html/vendor/craftcms/cms/src/web/View.php(597): craft\web\View->renderTemplate()
#15 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate()
#16 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format()
#17 /var/www/html/vendor/craftcms/cms/src/web/Response.php(339): yii\web\Response->prepare()
#18 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#19 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#20 /var/www/html/web/index.php(12): yii\base\Application->run()
#21 {main}

Next yii\db\Exception: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "field_validity" does not exist
LINE 8: ... NULL) AND ("elements"."revisionId" IS NULL) AND ("field_val...
                                                             ^
The SQL being executed was: SELECT COUNT(*)
FROM "craft_elements" "elements"
INNER JOIN "craft_entries" "entries" ON "entries"."id" = "elements"."id"
INNER JOIN "craft_elements_sites" "elements_sites" ON "elements_sites"."elementId" = "elements"."id"
LEFT JOIN "craft_structureelements" "structureelements" ON ("structureelements"."elementId" = "elements"."id") AND (EXISTS (SELECT *
FROM "craft_structures"
WHERE ("id" = "structureelements"."structureId") AND ("dateDeleted" IS NULL)))
WHERE ("entries"."typeId"=14) AND ("elements_sites"."siteId"=1) AND ((("elements"."enabled"=TRUE) AND ("elements_sites"."enabled"=TRUE)) AND ("entries"."postDate" <= '2024-12-15 14:10:59') AND (("entries"."expiryDate" IS NULL) OR ("entries"."expiryDate" > '2024-12-15 14:10:59'))) AND ("elements"."archived"=FALSE) AND ("elements"."dateDeleted" IS NULL) AND ("elements"."draftId" IS NULL) AND ("elements"."revisionId" IS NULL) AND ("field_validity"::json->>'end' > '2024-12-14 23:00:00') in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException()
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute()
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(443): yii\db\Command->queryInternal()
#3 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2204): yii\db\Command->queryScalar()
#4 /var/www/html/vendor/yiisoft/yii2/db/Query.php(368): craft\elements\db\ElementQuery->queryScalar()
#5 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1834): yii\db\Query->count()
#6 /var/www/html/vendor/craftcms/cms/src/web/twig/Extension.php(1297): craft\elements\db\ElementQuery->count()
#7 /var/www/html/craftcms/storage/runtime/compiled_templates/cd/cd1962c1f56865a98b8fda8092c75b76.php(54): craft\web\twig\Extension->lengthFilter()
#8 /var/www/html/vendor/twig/twig/src/Template.php(393): __TwigTemplate_56f5971aba4fc24e0a1d37fb041ed5d6->doDisplay()
#9 /var/www/html/vendor/twig/twig/src/Template.php(349): Twig\Template->yield()
#10 /var/www/html/vendor/twig/twig/src/Template.php(364): Twig\Template->display()
#11 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(35): Twig\Template->render()
#12 /var/www/html/vendor/twig/twig/src/Environment.php(306): Twig\TemplateWrapper->render()
#13 /var/www/html/vendor/craftcms/cms/src/web/View.php(544): Twig\Environment->render()
#14 /var/www/html/vendor/craftcms/cms/src/web/View.php(597): craft\web\View->renderTemplate()
#15 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate()
#16 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format()
#17 /var/www/html/vendor/craftcms/cms/src/web/Response.php(339): yii\web\Response->prepare()
#18 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#19 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#20 /var/www/html/web/index.php(12): yii\base\Application->run()
#21 {main}
Additional Information:
Array
(
    [0] => 42703
    [1] => 7
    [2] => ERROR:  column "field_validity" does not exist
LINE 8: ... NULL) AND ("elements"."revisionId" IS NULL) AND ("field_val...
                                                             ^
)
```

@yoannisj

**Comment by janhenckens** [comment]
Could you add which version of Craft & the plugin you are running (on both sites) @denisyilmaz? Thanks!

**Comment by denisyilmaz** [comment]
@janhenckens We are using Craft CMS `5.5.6.1` with Date Range Field `5.0.0-beta.3` for both projects.

**Comment by janhenckens** [comment]
Just tagged 5.0.0-beta.4 with a fix for this, can you update and try again?
Be sure to comment should be you still have an issue!

**Comment by denisyilmaz** [comment]
@janhenckens its working great. thanks for that quick fix

**Comment by janhenckens** [comment]
Cheers!
